CREATE TABLE player
(
  id INT PRIMARY KEY NOT NULL,
  status VARCHAR(10) NOT NULL,
  hand VARCHAR(4) NOT NULL,
  tabId INT NOT NULL
);
CREATE TABLE tab
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  nom VARCHAR(255) NOT NULL,
  pot INT DEFAULT 0,
  cartes VARCHAR(10)
);
CREATE TABLE user
(
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  unixid VARCHAR(32) NOT NULL,
  nom VARCHAR(32) NOT NULL,
  lastAct TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  solde INT NOT NULL
);
ALTER TABLE player ADD FOREIGN KEY (id) REFERENCES user (id);
ALTER TABLE player ADD FOREIGN KEY (tabId) REFERENCES tab (id);
CREATE INDEX player ON player (tabId);
CREATE UNIQUE INDEX unique_nom ON tab (nom);
CREATE UNIQUE INDEX unique_nom ON user (nom);
CREATE UNIQUE INDEX unique_unixid ON user (unixid);
